[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan config:cache && php artisan route:cache && php artisan migrate --force && php artisan storage:link --force && php -d upload_max_filesize=15M -d post_max_size=20M artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 120
